---
version: '3.6'
services:
  # The environment variable "TAG" is used throughout this file to
  # specify the version of the images to run. The default is set in the
  # '.env' file in this folder. It can be overridden with any normal
  # technique for setting environment variables, for example:
  #
  #   TAG=6.0.0-beta1 docker-compose up
  #
  # REF: https://docs.docker.com/compose/compose-file/#variable-substitution
  #
  # Also be sure to set the ELASTIC_VERSION variable. For released versions,
  # ${TAG} and ${ELASTIC_VERSION} will be identical, but for pre-release
  # versions, ${TAG} might contain an extra build identifier, like
  # "6.0.0-beta1-3eab5b40", so a full invocation might look like:
  #
  #   ELASTIC_VERSION=6.0.0-beta1 TAG=6.0.0-beta1-3eab5b40 docker-compose up
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    ports: ['9200:9200']
    networks: ['stack']
    # volumes:
    #   - ./snapshots:/snapshots:rw
    environment:
      # - path.repo=/snapshots
      - node.name=elastic-node-1
      - cluster.initial_master_nodes=elastic-node-1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    ports: ['5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  apm-server:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: apm_server
    ports: ['8200:8200']
    networks: ['stack']
    command: -E apm-server.rum.enabled=true --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    depends_on: ['elasticsearch', 'kibana']

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    networks: ['stack']
    depends_on: ['elasticsearch']
    volumes:
      - ./heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]

  petclinic:
    image: openjdk:8-jre-alpine
    container_name: petclinic
    networks: ['stack']
    ports: ['8080:8080']
    volumes:
      - ./elastic-apm-agent-1.7.0.jar:/tmp/elasticapmagent.jar:ro
      - ./tmp:/tmp:rw
      - ./target:/tmp/target:ro
    command: ["java", "-Delastic.apm.server_urls=http://apm-server:8200", "-Delastic.apm.application_packages=org.springframework.samples", "-Delastic.apm.service_name=spring-petclinic-monolith" ,"-javaagent:/tmp/elasticapmagent.jar", "-jar", "/tmp/target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar"]

  nginx:
    image: nginx:latest
    container_name: nginx
    networks: ['stack']
    ports: ['8081:80']
    depends_on: ["petclinic", "apm-server"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks: {stack: {}}
# use docker volume to persist ES data outside of a container.
#volumes:
#  es_data:
